substitutions:
  name: uart-sniffer
  rx_pin: GPIO5
  rx_pin2: GPIO4

esphome:
  name: ${name}
  min_version: 2024.6.0

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  level: DEBUG

api:
  reboot_timeout: 0s

packages:
  web: !include included/web.yaml

uart:
  - id: uart_0
    baud_rate: 2400
    rx_pin: ${rx_pin}
    debug:
      direction: RX
      dummy_receiver: true

   #   after:
    #    delimiter: "\n"
    #  sequence:
    #    - lambda: UARTDebug::log_string(direction, bytes);
      sequence:
        - lambda: UARTDebug::log_hex(esphome::uart::UARTDirection::UART_DIRECTION_RX, bytes, ':');

  - id: uart_1
    baud_rate: 2400
    rx_pin: ${rx_pin2}
    debug:
      direction: RX
      dummy_receiver: true
    #  after:
    #    delimiter: "\n"
    # sequence:
    #    - lambda: UARTDebug::log_string(direction, bytes);

      sequence:
        - lambda: UARTDebug::log_hex(esphome::uart::UARTDirection::UART_DIRECTION_TX, bytes, ':');

select:
  - id: change_baud_rate
    name: Baud rate
    platform: template
    options:
      - "300"
      - "600"
      - "1200"
      - "2400"
      - "9600"
      - "38400"
      - "57600"
      - "115200"
      - "256000"
      - "512000"
      - "921600"
    initial_option: "2400"
    optimistic: true
    restore_value: True
    internal: false
    entity_category: config
    icon: mdi:swap-horizontal
    set_action:
      - lambda: |-
          id(uart_0).flush();
          uint32_t new_baud_rate = stoi(x);
          ESP_LOGD("change_baud_rate", "Changing baud rate from %i to %i",id(uart_0).get_baud_rate(), new_baud_rate);
          if (id(uart_0).get_baud_rate() != new_baud_rate) {
            id(uart_0).set_baud_rate(new_baud_rate);
            id(uart_0).load_settings();
          }
          id(uart_1).flush();
          ESP_LOGD("change_baud_rate", "Changing baud rate from %i to %i",id(uart_1).get_baud_rate(), new_baud_rate);
          if (id(uart_1).get_baud_rate() != new_baud_rate) {
            id(uart_1).set_baud_rate(new_baud_rate);
            id(uart_1).load_settings();
          }