#-------------------------------------------
# EXTERNAL COMPONENT
#-------------------------------------------
external_components:
  - source: github://ananyevgv/esphome-components
    components: [mq]
    refresh: 0s
    
#-------------------------------------------
# SENSOR MQ-4
#-------------------------------------------
sensor:
  - platform: mq
    model: MQ7
    pin: $MQPin
    r0: $RationClearAir
    rl: $R2PCB
    update_interval: 30s
    sensor_lpg:
      name: Sensor LPG
    sensor_co:
      name: Sensor CO
      id: gas_co
    sensor_ch4:
      name: Sensor CH4
      id: gas_ch4
    sensor_h2:
      name: Sensor H2
    sensor_alcohol:
      name: Sensor ALCOHOL


#-------------------------------------------
# BINARY SENSOR 
#-------------------------------------------  
binary_sensor:
  - platform: template
    name: "Gas CH4"
    device_class: gas
    lambda: |-
      if (id(gas_ch4).state > 1500) {
        return true;
      } else {
        return false;
      }
    on_press:
    #  - switch.turn_on: close_gas
    #  - delay: 1s
      - switch.turn_off: close_gas
      
  - platform: template
    name: "Gas CO"
    device_class: gas
    lambda: |-
      if (id(gas_co).state > 17) {
        return true;
      } else {
        return false;
      }


#-------------------------------------------
# SWITCH
#-------------------------------------------
switch:
  - platform: gpio
    pin: $GPIO_Close_gas
    name: "Close_gas"
    id: close_gas